CJ_LINK_TYPE_BANNER = 1
CJ_LINK_TYPE_ADVANCED = 2
CJ_LINK_TYPE_TEXT = 3
CJ_LINK_TYPE_CONTENT = 4
CJ_LINK_TYPE_SMART = 5
CJ_LINK_TYPE_CATALOG = 6
CJ_LINK_TYPE_SMARTZONE = 7
CJ_LINK_TYPE_KEYWORD = 8
CJ_LINK_TYPES = (
    (CJ_LINK_TYPE_BANNER, 'Banner'),
    (CJ_LINK_TYPE_ADVANCED, 'Advanced Link'),
    (CJ_LINK_TYPE_TEXT, 'Text Link'),
    (CJ_LINK_TYPE_CONTENT, 'Content Link'),
    (CJ_LINK_TYPE_SMART, 'Smart Link'),
    (CJ_LINK_TYPE_CATALOG, 'Product Catalog'),
    (CJ_LINK_TYPE_SMARTZONE, 'Advertiser SmartZone'),
    (CJ_LINK_TYPE_KEYWORD, 'Keyword Link'),
)

CJ_PROMOTION_TYPE_COUPON = 1
CJ_PROMOTION_TYPE_SWEEPSTAKES = 1
CJ_PROMOTION_TYPE_PRODUCT = 1
CJ_PROMOTION_TYPE_SALE = 1
CJ_PROMOTION_TYPE_FREE_SHIPPING = 1
CJ_PROMOTION_TYPE_SEASONAL = 1
CJ_PROMOTION_TYPES = (
    (CJ_PROMOTION_TYPE_COUPON, 'coupon'),
    (CJ_PROMOTION_TYPE_SWEEPSTAKES, 'sweepstakes'),
    (CJ_PROMOTION_TYPE_PRODUCT, 'product'),
    (CJ_PROMOTION_TYPE_SALE, 'sale/discount'),
    (CJ_PROMOTION_TYPE_FREE_SHIPPING, 'free shipping'),
    (CJ_PROMOTION_TYPE_SEASONAL, 'seasonal link'),
)