CJ_LINK_TYPE_BANNER = 'Banner'
CJ_LINK_TYPE_ADVANCED = 'Advanced Link'
CJ_LINK_TYPE_TEXT = 'Text Link'
CJ_LINK_TYPE_CONTENT = 'Content Link'
CJ_LINK_TYPE_SMART = 'Smart Link'
CJ_LINK_TYPE_CATALOG = 'Product Catalog'
CJ_LINK_TYPE_SMARTZONE = 'Advertiser SmartZone'
CJ_LINK_TYPE_KEYWORD = 'Keyword Link'
CJ_LINK_TYPES = (CJ_LINK_TYPE_BANNER, CJ_LINK_TYPE_ADVANCED, CJ_LINK_TYPE_TEXT, CJ_LINK_TYPE_CONTENT, CJ_LINK_TYPE_SMART,
                 CJ_LINK_TYPE_CATALOG, CJ_LINK_TYPE_SMARTZONE, CJ_LINK_TYPE_KEYWORD)

CJ_PROMOTION_TYPE_COUPON = 'coupon'
CJ_PROMOTION_TYPE_SWEEPSTAKES = 'sweepstakes'
CJ_PROMOTION_TYPE_PRODUCT = 'product'
CJ_PROMOTION_TYPE_SALE = 'sale/discount'
CJ_PROMOTION_TYPE_FREE_SHIPPING = 'free shipping'
CJ_PROMOTION_TYPE_SEASONAL = 'seasonal link'
CJ_PROMOTION_TYPES = (CJ_PROMOTION_TYPE_COUPON, CJ_PROMOTION_TYPE_SWEEPSTAKES, CJ_PROMOTION_TYPE_PRODUCT, CJ_PROMOTION_TYPE_SALE,
                      CJ_PROMOTION_TYPE_FREE_SHIPPING, CJ_PROMOTION_TYPE_SEASONAL)

CJ_ACCOUNT_ACTIVE = 'Active'
CJ_ACCOUNT_DEACTIVE = 'Deactive'
CJ_ACCOUNT_STATUSES = (CJ_ACCOUNT_ACTIVE, CJ_ACCOUNT_DEACTIVE)

CJ_RELATIONSHIP_JOINED = 'joined'
CJ_RELATIONSHIP_NOT_JOINED = 'notjoined'
CJ_RELATIONSHIP_STATUSES = (CJ_RELATIONSHIP_JOINED, CJ_RELATIONSHIP_NOT_JOINED)